
package trng.loan.eligibility.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "LoanEligibilityService", targetNamespace = "http://www.example.org/LoanEligibilityService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoanEligibilityService {


    /**
     * 
     * @param loanEligibilityRequest
     * @return
     *     returns trng.loan.eligibility.service.LoanEligibilityResponseType
     */
    @WebMethod(action = "http://www.example.org/LoanEligibilityService/getLoanEligibility")
    @WebResult(name = "LoanEligibilityResponse", targetNamespace = "")
    @RequestWrapper(localName = "getLoanEligibility", targetNamespace = "http://www.example.org/LoanEligibilityService/", className = "trng.loan.eligibility.service.GetLoanEligibility")
    @ResponseWrapper(localName = "getLoanEligibilityResponse", targetNamespace = "http://www.example.org/LoanEligibilityService/", className = "trng.loan.eligibility.service.GetLoanEligibilityResponse")
    public LoanEligibilityResponseType getLoanEligibility(
        @WebParam(name = "LoanEligibilityRequest", targetNamespace = "")
        LoanEligibilityRequestType loanEligibilityRequest);

}
